# Change the number of threads
/run/numberOfThreads 4
#/control/cout/ignoreThreadsExcept 0

# Geometry

/Geometry/HPGeDetector_0/enable
/Geometry/HPGeDetector_0/position 0 0 25.4 cm

/Geometry/HPGeDetector_1/enable
/Geometry/HPGeDetector_1/rotateY 55 deg
/Geometry/HPGeDetector_1/position 20.81 0 14.62 cm

/Geometry/HPGeDetector_2/enable
/Geometry/HPGeDetector_2/rotateY 90 deg
/Geometry/HPGeDetector_2/position 25.4 0 0 cm

/Geometry/HPGeDetector_3/enable
/Geometry/HPGeDetector_3/rotateY 125 deg
/Geometry/HPGeDetector_3/position 20.81 0 -14.62 cm

/Geometry/HPGeDetector_4/enable
/Geometry/HPGeDetector_4/rotateY -30 deg
/Geometry/HPGeDetector_4/position -12.7 0 22.0 cm

/Geometry/TargetChamber/enable
/Geometry/TargetChamber/position 0 0 0 cm

/TargetChamber/setBackingMaterial G4_Ta

# Initialize
/run/initialize

# Beam energy
/gun/energy 10000 keV

# Run
/run/beamOn 10000
